export default [
  {
    ignores: [
      "node_modules/**",
      "../web/dist/**",
      "../web/pdfjs/**",
      "../chrome_extensions/incremento_companion/dist/**",
    ],
  },
  {
    files: ["**/*.{js,jsx,mjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        Blob: "readonly",
        Buffer: "readonly",
        CSS: "readonly",
        Element: "readonly",
        FileReader: "readonly",
        Headers: "readonly",
        Image: "readonly",
        MutationObserver: "readonly",
        Node: "readonly",
        ResizeObserver: "readonly",
        Response: "readonly",
        TextDecoder: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        atob: "readonly",
        btoa: "readonly",
        cancelAnimationFrame: "readonly",
        chrome: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        crypto: "readonly",
        document: "readonly",
        fetch: "readonly",
        globalThis: "readonly",
        location: "readonly",
        navigator: "readonly",
        process: "readonly",
        queueMicrotask: "readonly",
        requestAnimationFrame: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        structuredClone: "readonly",
        window: "readonly",
      },
    },
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
    rules: {
      "no-constant-binary-expression": "error",
      "no-dupe-keys": "error",
      "no-import-assign": "error",
      "no-self-assign": "error",
      "no-undef": "error",
      "no-unreachable": "error",
      "valid-typeof": "error",
    },
  },
];
