#!/usr/bin/env python3
"""Validate all gettext domains, then compile deterministic shipped MO catalogs.

Requires GNU gettext's msgfmt in the developer/CI environment, never in Anki.
--check compares generated bytes without changing the working tree.
"""
from __future__ import annotations

import argparse
import ast
import gettext
import io
from pathlib import Path
import re
import shutil
from string import Formatter
import subprocess
import sys


def _placeholders(message: str) -> set[tuple[str, str, str]]:
    fields = set()
    try:
        for _literal, name, spec, conversion in Formatter().parse(message):
            if name is None:
                continue
            if not re.fullmatch(r'[A-Za-z_][A-Za-z_0-9]*', name) or '{' in spec:
                raise ValueError(f'Unsafe placeholder: {name}')
            fields.add((name, spec, conversion or ''))
    except ValueError as exc:
        raise ValueError(f'Invalid placeholder: {exc}') from exc
    return fields


def _messages(data: bytes) -> dict[str, list[str]]:
    parsed = gettext.GNUTranslations(io.BytesIO(data))
    grouped: dict[str, list[str]] = {}
    # GNUTranslations has no public catalog iterator; isolate its binary catalog
    # representation here rather than implementing a second PO parser.
    for key, message in parsed._catalog.items():
        if key == '':
            continue
        message_id = key[0] if isinstance(key, tuple) else key
        grouped.setdefault(message_id, []).append(message)
    return grouped


def _validate_source_keys(root: Path, messages: dict[str, list[str]]) -> None:
    sources = [root / "__init__.py", *sorted((root / "backend").glob("*.py")), *sorted((root / "frontend").glob("*.py"))]
    missing = []
    for path in sources:
        if not path.is_file():
            continue
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Name):
                continue
            if node.func.id not in {"t", "tn", "_t", "_tn", "_tr"} or not node.args:
                continue
            key = node.args[0]
            if not isinstance(key, ast.Constant) or not isinstance(key.value, str):
                continue
            location = f"{path.relative_to(root)}:{node.lineno}: {key.value}"
            if key.value not in messages:
                missing.append(location)
                continue
            required = {name for name, _spec, _conversion in _placeholders(messages[key.value][0])}
            supplied = {kw.arg for kw in node.keywords}
            if node.func.id in {"tn", "_tn"} and len(node.args) > 1:
                supplied.add("count")
            # A spread mapping is checked by the runtime formatter. Literal
            # calls can be proved complete without executing addon code.
            if None not in supplied and required - supplied:
                missing.append(f"{location}: missing placeholders {sorted(required - supplied)}")
    if missing:
        raise ValueError("Source translation errors (keys or placeholders):\n" + "\n".join(missing))


def compile_catalogs(repo_root: Path, *, check: bool = False) -> int:
    msgfmt = shutil.which('msgfmt')
    if msgfmt is None:
        raise ValueError('GNU gettext msgfmt is required (brew install gettext / apt install gettext).')
    root = repo_root / 'locales'
    sources = sorted(root.glob('*/LC_MESSAGES/incremento*.po'))
    if not sources:
        raise ValueError('No translation catalogs found.')
    compiled: dict[Path, bytes] = {}
    messages: dict[tuple[str, str], dict[str, list[str]]] = {}
    locale_domains: dict[str, set[str]] = {}
    for path in sources:
        if any(part.is_symlink() for part in (path, *path.parents) if part != repo_root.parent):
            raise ValueError(f'Symlink catalog is not allowed: {path.relative_to(repo_root)}')
        result = subprocess.run([msgfmt, '--check-format', '--check-header', '--endianness=little', '-o', '-', str(path)], capture_output=True)
        if result.returncode:
            raise ValueError(result.stderr.decode('utf-8', errors='replace').strip())
        locale = path.parent.parent.name
        domain = path.stem
        compiled[path.with_suffix('.mo')] = result.stdout
        messages[locale, domain] = _messages(result.stdout)
        locale_domains.setdefault(locale, set()).add(domain)
    domains = locale_domains.get('en', set())
    if not domains:
        raise ValueError('English fallback catalogs are required.')
    owners: dict[str, str] = {}
    for domain in sorted(domains):
        for key, variants in messages['en', domain].items():
            if key in owners:
                raise ValueError(f'Duplicate translation ID {key} in {domain} and {owners[key]}')
            owners[key] = domain
            if not re.fullmatch(r'[A-Za-z][A-Za-z0-9_]*', key):
                raise ValueError(f'Invalid stable message ID: {key}')
            reference = _placeholders(variants[0])
            if any(_placeholders(value) != reference for value in variants):
                raise ValueError(f'Plural placeholder mismatch: en/{domain}/{key}')
    for locale, available in locale_domains.items():
        if available != domains:
            raise ValueError(f'Catalog domains differ from English: {locale}')
        for domain in sorted(domains):
            reference = messages['en', domain]
            translated = messages[locale, domain]
            if reference.keys() != translated.keys():
                raise ValueError(f'Catalog keys differ from English: {locale}/{domain}; missing={sorted(reference.keys() - translated.keys())}, extra={sorted(translated.keys() - reference.keys())}')
            for key, variants in translated.items():
                fields = _placeholders(reference[key][0])
                if any(_placeholders(value) != fields for value in variants):
                    raise ValueError(f'Placeholder mismatch: {locale}/{domain}/{key}')
    _validate_source_keys(repo_root, {
        key: messages['en', domain][key] for key, domain in owners.items()
    })
    # Validate every catalog before writing any output, so a bad translation
    # cannot leave a half-updated language in the distributable tree.
    for path in compiled:
        if path.is_symlink():
            raise ValueError(f'Symlink catalog is not allowed: {path.relative_to(repo_root)}')
    if check:
        stale = [str(path.relative_to(repo_root)) for path, data in compiled.items() if not path.is_file() or path.read_bytes() != data]
        if stale:
            raise ValueError('Stale compiled catalogs; run scripts/compile_i18n.py:\n' + '\n'.join(stale))
    else:
        for path, data in compiled.items():
            path.write_bytes(data)
    return len(compiled)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo-root', type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        count = compile_catalogs(args.repo_root.resolve(), check=args.check)
    except (OSError, ValueError, SyntaxError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f'{count} translation catalogs validated' + (' (compiled files match).' if args.check else ' and compiled.'))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
